apiVersion: v1
kind: Service
metadata:
  name: boolio-api
  labels:
    app: boolio-api
  namespace: boolio
spec:
  ports:
  - port: 80
    name: web
    targetPort: 4000
  selector:
    app: boolio-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boolio-api
  labels:
    app: boolio-api
  namespace: boolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boolio-api
  template:
    metadata:
      labels:
        app: boolio-api
    spec:
      containers:
      - name: boolio-api
        image: <IMAGE_NAME>
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: boolio-postgres
  labels:
    app: boolio-postgres
  namespace: boolio
spec:
  ports:
  - port: 5432
    name: postgres
    targetPort: 5432
  selector:
    app: boolio-postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boolio-postgres
  namespace: boolio
spec:
  selector:
    matchLabels:
      app: boolio-postgres
    serviceName: "boolio-postgres"
    replicas: 1
    template:
      metadata:
        labels:
          app: boolio-postgres
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: postgres
          image: postgres:10.11-alpine
          env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: boolio-creds
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: boolio-creds
                key: password
          ports:
          - containerPort: 5432
            name: postgres
          volumeMounts:
          - name: postgres-db-data
            mountPath: /data

